name: Test

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run phpcs
        run: composer run lint

  phpunit:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_DATABASE: wordpress_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          tools: composer
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Run test suite
        env:
          WP_TESTS_DB_HOST: 127.0.0.1
        run: vendor/bin/phpunit

      - name: Run multisite test suite
        if: hashFiles('tests/phpunit/multisite.xml') != ''
        env:
          WP_TESTS_DB_HOST: 127.0.0.1
        run: vendor/bin/phpunit -c tests/phpunit/multisite.xml
